### PR TITLE
Removed (print jobs) from add-to-pool

### PR DESCRIPTION
**Pull request by JonathanSmith**
On my machine this caused the thread pool to hang when under reasonably heavy load, so I removed the print statement and that fixed it. (Using SBCL 1.0.48 through SLIME and Emacs).

### CODE REVIEW

**Comment by kiuma** [comment]
Hi, do you have a test case ?

2011/9/21 Jonathan A Smith <
reply@reply.github.com>

**Comment by JonathanSmith** [comment]
I'm sorry, I'm starting to think this bug i'm experiencing is based in something else.

My test case currently involves firing up some code I have (lisp-on-yaws) and bombarding a 'static' page it with requests from a browser. It currently is looking like it is not a bug in this library, but something to do with SBCL occasionally 'dropping' a condition-wait/condition-notify. Basically; the 'main-thread' misses a condition-notify, and it gets stuck with something in the queue. 

(Last night I thought I had an easy fix, but it turned out I had just screwed up my test case to be single threaded).

I'll see if I can develop a better test case tonight.

**Comment by JonathanSmith** [comment]
Hi, 

So basically the issue is that SBCL Threads and Bordeaux Threads have different opinions on condition-wait and condition notify. This is a problem because Bordeaux Threads basically just reuses the SBCL primitives. I think what I've been encountering is a "Lost Wakeup" problem:

> "To avoid the "lost wakeup" problem, the implementation must guarantee that CONDITION-WAIT in thread A atomically releases the lock and sleeps. If this is not guaranteed there is the possibility that thread B can add an event and call CONDITION-NOTIFY between the lock release and the sleep - in this case the notify call would not see A, which would be left sleeping despite there being an event available.

If you look at the sbcl manual for condition-notify and condition-wait, it says:

> *when calling condition-wait, you must hold the mutex. condition-wait will drop the mutex while it waits, and obtain it again before returning for whatever reason;
> *likewise, you must be holding the mutex around calls to condition-notify;
> a process may return from condition-wait in several circumstances: it is not guaranteed that the underlying condition has become true. You must check that the resource is ready for whatever you want to do to it.

http://www.sbcl.org/manual/#Waitqueue_002fcondition-variables

The original code didn't wrap condition notifies in the appropriate lock, so if you were making a lot of requests, it was possible to call condition notify at the wrong time and hang the main thread (before it had released the lock or slept).

**Comment by kiuma** [comment]
thank you very much, this is why I love open source !

I've applied your patch.

I'll do some tests and soon release v0.3 version for quick lisp.

p.s. I've added again (print jobs) since it wasn't harmful.

Cheers,
kiuma

2011/9/22 Jonathan A Smith <
reply@reply.github.com>

**Pull request merged**
